# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network :private_network, ip: "192.168.34.2"  
  config.vm.provision :shell, path: "bootstrap.sh"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

end
