---
- name: Installs mysql
  apt: pkg={{ item }} state=installed update_cache={{ apt_update_cache }}
  with_items:
    - mysql-server
    - python-mysqldb

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: set root@locahost password (as root needs to set the plugin = mysql_native_password as well)
  shell: mysql -e "alter user root@localhost identified with 'mysql_native_password' by '{{ root_db_password }}';"
  changed_when: false

#- name: update mysql root password for all root accounts
#  mysql_user: name=root host={{ item }} password={{ root_db_password }}
#  with_items:
#    - localhost

# needs to be after 'update mysql root password for all root accounts'
- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent login_user=root login_password={{ root_db_password }}

- name: set character-set-server to utf-8
  copy: src=utf8.cnf dest=/etc/mysql/conf.d/



## mysql import data

- name: Ensure example database exists.
  mysql_db: name=wordpress_prod state=present
  register: check_db

- name: Ensure example database exists.
  mysql_db: name=etherpad state=present

- name: copy file
  copy: src=mysql.sql.bz2 dest=/tmp/mysql.sql.bz2
  when: check_db.changed

- name: create schema
  shell: bunzip2 /tmp/mysql.sql.bz2 -c | mysql && rm /tmp/mysql.sql.bz2
  when: check_db.changed

### mysql user usr_wordpress_prod

- name: create user usr_wordpress_prod
  mysql_user: append_privs=yes state=present name=usr_wordpress_prod host=localhost password="{{ usr_wordpress_prod_password }}" priv="{{ item }}:select,insert,update,delete,CREATE,DROP,ALTER"
  with_items:
    - wordpress_prod.*

- name: create user usr_etherpad
  mysql_user: append_privs=yes state=present name=usr_etherpad host=localhost password="{{ usr_etherpad_password }}" priv="{{ item }}:select,insert,update,delete,CREATE,DROP,ALTER"
  with_items:
    - etherpad.*


